import java.util.Scanner;

public class salesPrediction {
	
	public static void main (String args[]) {
		
		Scanner keyboard = new Scanner(System.in);
		Double tSales;
		Double pSales;
		
		System.out.printf("The East Coast division makes 62 percent of the sales %n", args);
		
		System.out.printf("Enter how many millions were earned in toatl sales (ex: 4.2) to get the amount generated by the East Coast division: ", args);
		tSales = Double.parseDouble(keyboard.next());
		
		pSales = (tSales*0.62)*1000000;
		
		System.out.printf("The total sales for the year are %.2f million %n The Ease Coast division generated %.2f of that total", tSales, pSales);
		
	}

}
